2019-06-07 16:29:26 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2019-06-07 16:30:31 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2019-06-07 16:32:47 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:90)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2787)
	at org.h2.mvstore.MVStore.panic(MVStore.java:441)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:404)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]" [50000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/khanh/Dropbox/data/Source/ReportAdmin/web-backend/reportWS/run/database.mv.db [1.4.199/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:390)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2019-06-07 16:37:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT FROM AM_USER [*]"; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from am_user [42001-199]
2019-06-07 16:37:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT FROM AM_USER [*]"; expected "., (, USE, AS, RIGHT, LEFT, FULL, INNER, JOIN, CROSS, NATURAL, ,, SELECT"; SQL statement:
select from am_user [42001-199]
2019-06-07 17:16:45 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "khanhlv" not found; SQL statement:
INSERT INTO  am_user (user_name, password ,status)
VALUES ("khanhlv","VvkVxQ2Rc/WzHNl13y3XonCq68c=",1 ) [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Insert.prepare(Insert.java:322)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-06-07 17:18:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "INSERT INTO  AM_USER (USER_NAME, PASSWORD ,STATUS)
VALUES (KHANHLV,VVKVXQ2RC/WZHNL13Y3XONCQ68C=,[*]1 ) "; expected "ALL, ANY, SOME"; SQL statement:
INSERT INTO  am_user (user_name, password ,status)
VALUES (khanhlv,VvkVxQ2Rc/WzHNl13y3XonCq68c=,1 ) [42001-199]
2019-06-07 17:35:12 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" not found; SQL statement:
SELECT * FROM AM_USER [42102-199]
2019-06-07 17:35:13 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" not found; SQL statement:
SELECT * FROM AM_USER [42102-199]
2019-06-07 17:35:13 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" not found; SQL statement:
SELECT * FROM AM_USER [42102-199]
2019-06-07 17:37:43 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ""AM_USER"" 
   (	""USER_ID"" NUMBER(10,0) PRIMARY,[*] 
	""ADDRESS"" VARCHAR2(512 CHAR), 
	""AUTH_METHOD"" VARCHAR2(20 CHAR), 
	""CREATED_ID"" NUMBER(10,0), 
	""CREATED_TIME"" DATE, 
	""DELETED_ID"" NUMBER(10,0), 
	""EMAIL"" VARCHAR2(50 CHAR), 
	""EXPIRE_STATUS"" NUMBER(1,0), 
	""FAILURE_COUNT"" NUMBER(5,0), 
	""FAX"" VARCHAR2(15 CHAR), 
	""FULL_NAME"" VARCHAR2(100 CHAR), 
	""LOCKED_DATE"" DATE, 
	""MOBILE"" VARCHAR2(15 CHAR), 
	""MODIFIED_ID"" NUMBER(10,0), 
	""MODIFIED_PASSWORD"" DATE, 
	""PASSWORD"" VARCHAR2(100 CHAR), 
	""PASSWORD_BACKUP"" VARCHAR2(50 CHAR), 
	""PHONE"" VARCHAR2(15 CHAR), 
	""PRIORITY"" NUMBER(5,0), 
	""RIGHT_TYPE"" NUMBER(19,0), 
	""STATUS"" NUMBER(1,0), 
	""USER_NAME"" VARCHAR2(50 CHAR), 
	""DOCUMENT"" CLOB
   ) "; expected "KEY"; SQL statement:
CREATE TABLE "AM_USER" 
   (	"USER_ID" NUMBER(10,0) primary, 
	"ADDRESS" VARCHAR2(512 CHAR), 
	"AUTH_METHOD" VARCHAR2(20 CHAR), 
	"CREATED_ID" NUMBER(10,0), 
	"CREATED_TIME" DATE, 
	"DELETED_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"EXPIRE_STATUS" NUMBER(1,0), 
	"FAILURE_COUNT" NUMBER(5,0), 
	"FAX" VARCHAR2(15 CHAR), 
	"FULL_NAME" VARCHAR2(100 CHAR), 
	"LOCKED_DATE" DATE, 
	"MOBILE" VARCHAR2(15 CHAR), 
	"MODIFIED_ID" NUMBER(10,0), 
	"MODIFIED_PASSWORD" DATE, 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PASSWORD_BACKUP" VARCHAR2(50 CHAR), 
	"PHONE" VARCHAR2(15 CHAR), 
	"PRIORITY" NUMBER(5,0), 
	"RIGHT_TYPE" NUMBER(19,0), 
	"STATUS" NUMBER(1,0), 
	"USER_NAME" VARCHAR2(50 CHAR), 
	"DOCUMENT" CLOB
   ) [42001-199]
2019-06-07 17:38:41 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE ""AM_USER"" 
   (	""USER_ID"" NUMBER(10,0)  
	""ADDRESS""[*] VARCHAR2(512 CHAR), 
	""AUTH_METHOD"" VARCHAR2(20 CHAR), 
	""CREATED_ID"" NUMBER(10,0), 
	""CREATED_TIME"" DATE, 
	""DELETED_ID"" NUMBER(10,0), 
	""EMAIL"" VARCHAR2(50 CHAR), 
	""EXPIRE_STATUS"" NUMBER(1,0), 
	""FAILURE_COUNT"" NUMBER(5,0), 
	""FAX"" VARCHAR2(15 CHAR), 
	""FULL_NAME"" VARCHAR2(100 CHAR), 
	""LOCKED_DATE"" DATE, 
	""MOBILE"" VARCHAR2(15 CHAR), 
	""MODIFIED_ID"" NUMBER(10,0), 
	""MODIFIED_PASSWORD"" DATE, 
	""PASSWORD"" VARCHAR2(100 CHAR), 
	""PASSWORD_BACKUP"" VARCHAR2(50 CHAR), 
	""PHONE"" VARCHAR2(15 CHAR), 
	""PRIORITY"" NUMBER(5,0), 
	""RIGHT_TYPE"" NUMBER(19,0), 
	""STATUS"" NUMBER(1,0), 
	""USER_NAME"" VARCHAR2(50 CHAR), 
	""DOCUMENT"" CLOB,  PRIMARY KEY (""USER_ID"")
   )"; expected "FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE "AM_USER" 
   (	"USER_ID" NUMBER(10,0)  
	"ADDRESS" VARCHAR2(512 CHAR), 
	"AUTH_METHOD" VARCHAR2(20 CHAR), 
	"CREATED_ID" NUMBER(10,0), 
	"CREATED_TIME" DATE, 
	"DELETED_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"EXPIRE_STATUS" NUMBER(1,0), 
	"FAILURE_COUNT" NUMBER(5,0), 
	"FAX" VARCHAR2(15 CHAR), 
	"FULL_NAME" VARCHAR2(100 CHAR), 
	"LOCKED_DATE" DATE, 
	"MOBILE" VARCHAR2(15 CHAR), 
	"MODIFIED_ID" NUMBER(10,0), 
	"MODIFIED_PASSWORD" DATE, 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PASSWORD_BACKUP" VARCHAR2(50 CHAR), 
	"PHONE" VARCHAR2(15 CHAR), 
	"PRIORITY" NUMBER(5,0), 
	"RIGHT_TYPE" NUMBER(19,0), 
	"STATUS" NUMBER(1,0), 
	"USER_NAME" VARCHAR2(50 CHAR), 
	"DOCUMENT" CLOB,  PRIMARY KEY ("USER_ID")
   ) [42001-199]
2019-06-07 17:39:49 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" already exists; SQL statement:
CREATE TABLE "AM_USER" 
   (	"USER_ID" NUMBER(10,0)  IDENTITY PRIMARY KEY,
	"ADDRESS" VARCHAR2(512 CHAR), 
	"AUTH_METHOD" VARCHAR2(20 CHAR), 
	"CREATED_ID" NUMBER(10,0), 
	"CREATED_TIME" DATE, 
	"DELETED_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"EXPIRE_STATUS" NUMBER(1,0), 
	"FAILURE_COUNT" NUMBER(5,0), 
	"FAX" VARCHAR2(15 CHAR), 
	"FULL_NAME" VARCHAR2(100 CHAR), 
	"LOCKED_DATE" DATE, 
	"MOBILE" VARCHAR2(15 CHAR), 
	"MODIFIED_ID" NUMBER(10,0), 
	"MODIFIED_PASSWORD" DATE, 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PASSWORD_BACKUP" VARCHAR2(50 CHAR), 
	"PHONE" VARCHAR2(15 CHAR), 
	"PRIORITY" NUMBER(5,0), 
	"RIGHT_TYPE" NUMBER(19,0), 
	"STATUS" NUMBER(1,0), 
	"USER_NAME" VARCHAR2(50 CHAR), 
	"DOCUMENT" CLOB
   ) [42101-199]
2019-06-07 17:39:49 jdbc[14]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" already exists; SQL statement:
CREATE TABLE "AM_USER" 
   (	"USER_ID" NUMBER(10,0)  IDENTITY PRIMARY KEY,
	"ADDRESS" VARCHAR2(512 CHAR), 
	"AUTH_METHOD" VARCHAR2(20 CHAR), 
	"CREATED_ID" NUMBER(10,0), 
	"CREATED_TIME" DATE, 
	"DELETED_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"EXPIRE_STATUS" NUMBER(1,0), 
	"FAILURE_COUNT" NUMBER(5,0), 
	"FAX" VARCHAR2(15 CHAR), 
	"FULL_NAME" VARCHAR2(100 CHAR), 
	"LOCKED_DATE" DATE, 
	"MOBILE" VARCHAR2(15 CHAR), 
	"MODIFIED_ID" NUMBER(10,0), 
	"MODIFIED_PASSWORD" DATE, 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"PASSWORD_BACKUP" VARCHAR2(50 CHAR), 
	"PHONE" VARCHAR2(15 CHAR), 
	"PRIORITY" NUMBER(5,0), 
	"RIGHT_TYPE" NUMBER(19,0), 
	"STATUS" NUMBER(1,0), 
	"USER_NAME" VARCHAR2(50 CHAR), 
	"DOCUMENT" CLOB
   ) [42101-199]
2019-06-07 17:41:55 jdbc[17]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:299)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:782)
	at org.h2.server.web.WebApp.login(WebApp.java:1004)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 15 more
2019-06-07 17:43:03 jdbc[38]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "AM_USER" already exists; SQL statement:
CREATE TABLE "AM_USER"
   (	"USER_ID" NUMBER(10,0)  IDENTITY PRIMARY KEY,
	"ADDRESS" VARCHAR2(512 CHAR),
	"AUTH_METHOD" VARCHAR2(20 CHAR),
	"CREATED_ID" NUMBER(10,0),
	"CREATED_TIME" DATE,
	"DELETED_ID" NUMBER(10,0),
	"EMAIL" VARCHAR2(50 CHAR),
	"EXPIRE_STATUS" NUMBER(1,0),
	"FAILURE_COUNT" NUMBER(5,0),
	"FAX" VARCHAR2(15 CHAR),
	"FULL_NAME" VARCHAR2(100 CHAR),
	"LOCKED_DATE" DATE,
	"MOBILE" VARCHAR2(15 CHAR),
	"MODIFIED_ID" NUMBER(10,0),
	"MODIFIED_PASSWORD" DATE,
	"PASSWORD" VARCHAR2(100 CHAR),
	"PASSWORD_BACKUP" VARCHAR2(50 CHAR),
	"PHONE" VARCHAR2(15 CHAR),
	"PRIORITY" NUMBER(5,0),
	"RIGHT_TYPE" NUMBER(19,0),
	"STATUS" NUMBER(1,0),
	"USER_NAME" VARCHAR2(50 CHAR),
	"DOCUMENT" CLOB
   ) [42101-199]
2019-06-07 22:52:48 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:126)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 9 more
2019-06-10 11:00:50 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "khanhlv" not found; SQL statement:
insert into Se_resource(name) values("khanhlv") [42122-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.expression.ExpressionColumn.getColumnException(ExpressionColumn.java:176)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:158)
	at org.h2.command.dml.Insert.prepare(Insert.java:322)
	at org.h2.command.Parser.prepareCommand(Parser.java:689)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-06-10 11:01:41 jdbc[55]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "khanhlv"; SQL statement:
insert into Se_resource(name) values('khanhlv') [22018-199]
2019-06-10 11:04:59 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "NAME" must not be nullable; SQL statement:
alter table SE_RESOURCE ADD PRIMARY KEY (NAME) [90023-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.mvstore.db.MVTable.addIndex(MVTable.java:349)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:151)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-06-10 11:06:18 jdbc[55]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Unknown data type: "NOT"; SQL statement:
alter table SE_RESOURCE add column NAME not null [50004-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:5524)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:5254)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:7932)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:7586)
	at org.h2.command.Parser.parseAlterTable(Parser.java:7209)
	at org.h2.command.Parser.parseAlter(Parser.java:6546)
	at org.h2.command.Parser.parsePrepared(Parser.java:828)
	at org.h2.command.Parser.parse(Parser.java:788)
	at org.h2.command.Parser.parse(Parser.java:760)
	at org.h2.command.Parser.prepareCommand(Parser.java:683)
	at org.h2.engine.Session.prepareLocal(Session.java:627)
	at org.h2.engine.Session.prepareCommand(Session.java:565)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1113)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1436)
	at org.h2.server.web.WebApp.query(WebApp.java:1111)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1073)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1060)
	at org.h2.server.web.WebThread.process(WebThread.java:173)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-06-10 11:07:03 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "NAME[*] NAME"; SQL statement:
NAME NAME [42000-199]
2019-06-10 11:10:16 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE SE_OPERATION ADD PRIMARY KEY CODE[*] "; expected "HASH, ("; SQL statement:
alter table SE_OPERATION ADD PRIMARY KEY CODE [42001-199]
2019-06-10 11:22:39 jdbc[55]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE SE_PERMISSION DROP TABLE[*] NAME "; expected "identifier"; SQL statement:
alter table se_permission drop table name [42001-199]
2019-06-10 12:31:50 jdbc[151]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE DROP SE_ROLE[*] DROP COLUMN NAME "; expected "., ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
alter table drop SE_ROLE drop column name [42001-199]
2019-06-10 13:21:11 jdbc[194]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:242)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:182)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:299)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:782)
	at org.h2.server.web.WebApp.login(WebApp.java:1004)
	at org.h2.server.web.WebApp.process(WebApp.java:219)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:139)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 15 more
